In [1]:
import sys
import os

sys.path.append(os.path.abspath(".."))

In [2]:
import pandas as pd

df = pd.read_excel("../data/raw_data_retail.xlsx")
df.to_csv("../data/dataset.csv", index=False)

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [28]:
import os
print(os.listdir())

['basic_eda.ipynb']

In [ ]:
import os

print("Current dir:", os.getcwd())
print("Files here:", os.listdir())
print("Data folder:", os.listdir("data"))

In [ ]:
import os
print(os.listdir("data"))

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

Las columnas Description (object) y CustomerID (float64) poseen nulos

In [4]:
# Change type object or str to string to avoid future warnings
df["InvoiceNo"] = df["InvoiceNo"].astype("string")
df["StockCode"] = df["StockCode"].astype("string")
df["Description"] = df["Description"].astype("string")
df["Country"] = df["Country"].astype("string")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  string
 1   StockCode    541909 non-null  string
 2   Description  540455 non-null  string
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  string
dtypes: datetime64[us](1), float64(2), int64(1), string(4)
memory usage: 33.1 MB

In [5]:
# Convertir fechas
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
df.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom

In [6]:
print(f"Tengo {df.duplicated().sum()} filas duplicadas")

Tengo 5268 filas duplicadas

In [7]:
columnas_duplicadas=df.columns[df.columns.duplicated(keep=False)]
if any(columnas_duplicadas):
    print(f"Las columnas duplicadas son {list(columnas_duplicadas)}")
else:
    print("No hay columnas duplicadas en el DF")

No hay columnas duplicadas en el DF

In [8]:
# Identificación de filas duplicadas. Creación de un df con los duplicados
df[df.duplicated()].head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
587,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
589,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
594,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
600,536412,22569,FELTCRAFT CUSHION BUTTERFLY,2,2010-12-01 11:49:00,3.75,17920.0,United Kingdom

Podemos ver que los duplicados no son duplicados reales, ya pueden repetirse varios campos, sin embargo campos importantes como description cambian y esto ya me dice que cada registro es diferente uno del otro

In [9]:
df = df.dropna(subset=["CustomerID"])
df = df.dropna(subset=["Description"])
df.info()

<class 'pandas.DataFrame'>
Index: 406829 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    406829 non-null  string
 1   StockCode    406829 non-null  string
 2   Description  406829 non-null  string
 3   Quantity     406829 non-null  int64
 4   InvoiceDate  406829 non-null  datetime64[us]
 5   UnitPrice    406829 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      406829 non-null  string
dtypes: datetime64[us](1), float64(2), int64(1), string(4)
memory usage: 27.9 MB

In [10]:
# Filtrar devoluciones
df = df[~df["InvoiceNo"].str.startswith("C", na=False)]
df.info()

<class 'pandas.DataFrame'>
Index: 397924 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    397924 non-null  string
 1   StockCode    397924 non-null  string
 2   Description  397924 non-null  string
 3   Quantity     397924 non-null  int64
 4   InvoiceDate  397924 non-null  datetime64[us]
 5   UnitPrice    397924 non-null  float64
 6   CustomerID   397924 non-null  float64
 7   Country      397924 non-null  string
dtypes: datetime64[us](1), float64(2), int64(1), string(4)
memory usage: 27.3 MB

In [11]:
# Ver valores unicos de la columna InvoiceNo
print(f"Tengo {df['InvoiceNo'].nunique()} valores únicos en la columna InvoiceNo")

Tengo 18536 valores únicos en la columna InvoiceNo

In [12]:
# crear métricas útiles
df["TotalPrice"] = df["Quantity"] * df["UnitPrice"]
df["year"] = df["InvoiceDate"].dt.year
df["month"] = df["InvoiceDate"].dt.month
df["day"] = df["InvoiceDate"].dt.day
df["hour"] = df["InvoiceDate"].dt.hour
df.info()

<class 'pandas.DataFrame'>
Index: 397924 entries, 0 to 541908
Data columns (total 13 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    397924 non-null  string
 1   StockCode    397924 non-null  string
 2   Description  397924 non-null  string
 3   Quantity     397924 non-null  int64
 4   InvoiceDate  397924 non-null  datetime64[us]
 5   UnitPrice    397924 non-null  float64
 6   CustomerID   397924 non-null  float64
 7   Country      397924 non-null  string
 8   TotalPrice   397924 non-null  float64
 9   year         397924 non-null  int32
 10  month        397924 non-null  int32
 11  day          397924 non-null  int32
 12  hour         397924 non-null  int32
dtypes: datetime64[us](1), float64(3), int32(4), int64(1), string(4)
memory usage: 36.4 MB

In [14]:
df.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,year,month,day,hour
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,2010,12,1,8
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,1,8
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,2010,12,1,8
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,1,8
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,1,8
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom,15.30,2010,12,1,8
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom,25.50,2010,12,1,8
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom,11.10,2010,12,1,8
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom,11.10,2010,12,1,8
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom,54.08,2010,12,1,8

Metricas útiles:
Revenue per Invoice: df.groupby("InvoiceNo")["TotalPrice"].sum()
df["items_per_invoice"] = df.groupby("InvoiceNo")["Quantity"].transform("sum")
Unique products per Invoice: df["unique_products"] = df.groupby("InvoiceNo")["StockCode"].transform("nunique")
Metrica por cliente (util para segmentación): df["customer_total_spent"] = df.groupby("CustomerID")["TotalPrice"].transform("sum")
Frecuencia de compra: df["customer_orders"] = df.groupby("CustomerID")["InvoiceNo"].transform("nunique")

métricas base
df["TotalPrice"] = df["Quantity"] * df["UnitPrice"]

metricas tiempo
df["year"] = df["InvoiceDate"].dt.year
df["month"] = df["InvoiceDate"].dt.month
df["day"] = df["InvoiceDate"].dt.day
df["hour"] = df["InvoiceDate"].dt.hour

metricas invoice
df["items_per_invoice"] = df.groupby("InvoiceNo")["Quantity"].transform("sum")
df["unique_products"] = df.groupby("InvoiceNo")["StockCode"].transform("nunique")

metricas cliente
df["customer_total_spent"] = df.groupby("CustomerID")["TotalPrice"].transform("sum")
df["customer_orders"] = df.groupby("CustomerID")["InvoiceNo"].transform("nunique")

In [58]:
# save clean dataset
df.to_csv("../data/dataset_clean.csv", index=False)

In [ ]:
from src.tools.data_loader import load_data

df = load_data()
df.head()

BASE_DIR: C:\Users\gcruz_li35hm9\Desktop\ai-data-analyst-agent
DATA_PATH: C:\Users\gcruz_li35hm9\Desktop\ai-data-analyst-agent\data\dataset_clean.csv
Loading from: C:\Users\gcruz_li35hm9\Desktop\ai-data-analyst-agent\data\dataset_clean.csv

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,year,month,day,hour
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,2010,12,1,8
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,1,8
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,2010,12,1,8
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,1,8
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,1,8

:

In [67]:
from src.tools.data_loader import DATA_PATH

print(DATA_PATH)

data/dataset_clean.csv